apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline-deployment
  template:
    metadata:
      labels:
        app: pipeline-deployment
    spec:
      containers:
      - name: pipeline-deployment
        image: royjith/pikube:latest-v2.0
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: prod-streamlit-service
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501 
  selector:
    app: pipeline-deployment
